baseURL = "https://chandraauliatama.github.io/"
languageCode = "en-us"
title = "Chandra Blog"
theme = "ink"
paginate = 5

copyright = "© Copyright Made With Help By"

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-123-45"
disqusShortname = "ink-demo"

[params]
	subtitle = "Tempat Nulis Isi Pikiran"

	# Optional 64x64 avatar image.
	avatar = "/images/avatar1.jpg"

	# Content types to disable Disqus on.
	disableDisqusTypes = ["page", "posts"]
	
	featherIconsCDN = true

	mode = "auto" # "dark" or "auto"
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.

# Nav.
[[menu.main]]
name = "Beranda"
url = "/"
weight = 1

[[menu.main]]
name = "Semua Tulisan"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tentang"
url = "/about"
weight = 3

[[menu.main]]
name = "Tag"
url = "/tags"
weight = 4

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/chandraauliatama"

[[params.social]]
name = "Instagram"
icon = "instagram"
url = "https://www.instagram.com/chandraauliatama/"

[taxonomies]
   tag = "tags"
